### ISSUE TITLE
Make all genes in annotation available for searching

### ISSUE THREAD

**Issue by sjessa** [fungenomics/braindex#1]
And return more informative errors to distinguish when a gene is in the annotation but not detected, vs. not in the annotation at all

**Comment by sjessa** [comment]
An app that does this nicely: https://apps.kaessmannlab.org/evodevoapp/
It would be cool to:

1. Return a non-fatal error (just a message?) if the gene is not found, but exists in the annotation
2. Print, somewhere, synonyms of the genes, if that's easy to cross-check in other annotations...

**Comment by bhavyaac** [comment]
An idea for the future would be to produce a separate error message for inputs that only differ from accepted genes due to capitalization (since the validation is case-sensitive - see issue #17). This message could suggest the capitalization used by the app to the user, for example: `The input gene "CBx6" does not exist in this dataset. Did you mean "Cbx6"?` 
Furthermore, error messages may suggest gene names that are similar, for example: `The input gene "Cxb6 does not exist in this dataset. Did you mean "Cbx6"?`. This could also be expanded to display synonyms of genes that may not be present (as mentioned above).

**Comment by sjessa** [comment]
@bhavyaac That would be indeed be very cool! I think there are some different levels of difficulty/types of implementation here -- for the synonyms, we would have to find a database of synonyms of all the genes in our annotation. For making suggestions based on case-/whitespace-/letter-order-sensitivity, we may need to look into a fuzzy string matching tool. (I think these exist but I'd leave further work in those directions on the back burner for now!)

**Comment by bhavyaac** [comment]
I've just implemented this in the dendrogram tab (it's easy to transfer to the other tabs once I'm satisfied). 

**Behaviour:**

The user can now select any of the genes in the annotation through the text box. If a selected gene is in the annotation but not in the dataset, the following message appears (through `validate()`) `The input gene "Strc" is in the dataset annotation but no data exists for it.` If it's not in the annotation or the dataset, it will say: `The input gene "NotAGene" is not within the dataset nor the annotation.` All of this also applies to uploaded files.

**Notes: (some of these should be included in the wiki documentation later on)**

- I wasn't quite sure how to word the error messages, and I can definitely change them if they are unclear.
- I've tried producing both errors at the same time by putting "Strc" and "NotAGene" in the same input, and only the Strc error (i.e. not in dataset but in annotation) occurs regardless of the input order. I'm not sure if I should try to change it so that the second error (i.e. not in annotation or dataset) takes precedence instead. 
- If there are multiple genes provided as input that are within the same "category" of error, then error messages for all of them will show up at the same time.
- I saw that in the GRN app the genes outside of the dataset but within the annotation are simply listed in the sidebar, and plots made with the remaining genes appear as normal. I can try to implement that instead if it's more user-friendly.
- I'm wondering if there should be a toggle switch to only show genes that are in the dataset as text box choices...?

**Comment by sjessa** [comment]
I think this is going to be really helpful! I'll leave some of the discussion of details for later (such as error priority, and the toggle for showing genes in the dataset), but for know I just wanted to suggest two alternative wordings: 

If the gene is in the annotation, but not the dataset --> `The input gene "Strc" is in the gene annotation but was not detected in this dataset`.
If the gene is not in the annotation --> `The input gene "NotAGene" was not found in the gene annotation.`

In case it helps for some background, the "annotation" is basically a reference set of _all_ the genes and their genomic coordinates that we use, for every single-cell dataset in the lab, to count up the expression levels of each gene based on the sequencing data. The "dataset" is that matrix of expression values for every cell, but if a gene has 0 expression in most cells, it's not included in the matrix, so that's why a gene could be in the annotation but not the dataset.
