### ISSUE TITLE
Show number of cells expressing the gene in timecourse tooltip

### ISSUE THREAD

**Issue by bhavyaac** [fungenomics/braindex#19]
The interactive timecourse plot's tooltips currently show the cluster name on hover. It would also be useful to show the number of cells expressing the gene in that cluster, perhaps also with the total number of cells in the cluster. This would only show up in the hover that's on points, not on fills.
General idea: take the proportion value at each point and multiply by number of cells ~~in the cluster~~ Edit: in the timepoint(?)

**Comment by bhavyaac** [comment]
@sjessa I realized I might be misunderstanding the y-axis of the timecourse plot. Is the proportion value over all cells within the time point? I'm assuming so because the total number of cells used for calculating the proportion remains consistent for all cell types in a given time point. This is what the tooltip currently looks like (based on what I assumed), let me know if I should change it!
![Screenshot (201)](https://user-images.githubusercontent.com/26724860/123456624-0b460d00-d5b1-11eb-8f6b-9381f17e0065.png)

**Comment by bhavyaac** [comment]
Also, some cell types appear but show NA values in the tooltip. I'm not sure if I should replace them with zeroes or leave them as they are.
![Screenshot (200)](https://user-images.githubusercontent.com/26724860/123459588-7e04b780-d5b4-11eb-861e-e5858336ac1b.png)

**Comment by sjessa** [comment]
@bhavyaac Good questions!

For the first comment, yes, you're right, it's the proportion over _all_ cells in the timepoint (since the total height of the ribbon at that timepoint represents all cells). I think it looks good! If users find it confusing that the "total cells" value doesn't change, we could just show the # of cells within that cluster

For the second comment, I may be wrong but I think it may have been important to have each cluster represented at each timepoint in order to create the ribbons, hence the NA clusters in certain cases. But I can't recall for sure! Just to be aware, maybe that's one to test outside the app to see how it behaves :)
