### ISSUE TITLE
Add ability to cluster cell types based on mean expression of input genes

### ISSUE THREAD

**Issue by sjessa** [fungenomics/braindex#21]
Example:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/12974417/122500528-f40b8c00-cfc0-11eb-9057-25651aa108f0.png">

**Comment by bhavyaac** [comment]
Current plan for implementing this heatmap:
- Place in a separate tab (tentative name "Clustering based on gene expression"...?)
- Allow user to choose genes on y axis with the same gene input sidebar section as other tabs
- Display y axis genes NOT in the same order as user input, but rather in the order selected by the heatmap to optimize viewing of clusters within the data.  Also allow the same kind of clustering for the x axis i.e. the cluster labels
- Display a clustering hierarchy regarding the genes on the left side of the plot, like the figure in the comment above
- Use checkboxes / toggle switches to allow viewing of selected cell classes (less granular categories than clusters). Potentially add functionality to select clusters to show within a certain class as well in a nested fashion (if this is possible)

**Comment by bhavyaac** [comment]
Preview of current heat map:
<img width="1223" alt="Screen Shot 2021-07-26 at 3 31 44 PM" src="https://user-images.githubusercontent.com/26724860/127047636-f2ba2ee3-8764-490b-8e86-916dcc65c584.png">

I still need to work on:
- Decreasing the space at the top of the plot so that it's closer to the descriptive text
- Writing about the row rescaling that took place in heat map if necessary
- Ordering the clusters so that all ependymal cells are together and the cell classes are in a specific order
- Allowing viewing of clusters from only certain cell classes (see my previous comment)
- Potentially removing restrictions on which clusters are plotted (right now I'm using grep with `ASTR|EPEN|OL|OPC|EXN`) - this will make the heat map very wide...

**Comment by bhavyaac** [comment]
I've included a `validate()` statement in this tab to check for >1 gene inputs, since the plot will produces an error when given only 1 gene (I believe because heat map clustering is not possible in this case). Should I still try to make it work for only one gene, e.g. set clustering arguments of the heatmap to `FALSE` if there is only 1 gene provided as input?

**Comment by sjessa** [comment]
This is looking really cool! A couple comments/responses to your questions:

>  Should I still try to make it work for only one gene, e.g. set clustering arguments of the heatmap to FALSE if there is only 1 gene provided as input?

No, I think it's reasonable to only produce the heatmap for >1 valid gene!

> Ordering the clusters so that all ependymal cells are together and the cell classes are in a specific order

For this tab, what I'd recommend is to leave the clustering of the columns (cell types) on (`cluster_cols = TRUE`) so that we can see what clustering best highlights the patterns in the data. I think the users already have an option to view gene expression relative to the static cell types in the bubble plot, so the heatmap can allow for a different type of analysis of the data based on the input genes.

> Potentially removing restrictions on which clusters are plotted (right now I'm using grep with ASTR|EPEN|OL|OPC|EXN) - this will make the heat map very wide...

Agreed! I think we should definitely try and allow for options (as you suggested in the previous comment before this one) rather than filtering to this specific set (I think I did this in my example code for a particular biological question but it won't always be the case) -- maybe we could try to allow selecting by broad cell class?

**Comment by bhavyaac** [comment]
Here is an updated preview of the heat map:
<img width="1423" alt="Screen Shot 2021-07-28 at 12 27 27 PM" src="https://user-images.githubusercontent.com/26724860/127360553-2768e5e4-9607-44b0-af6d-6357a9f1a448.png">
I've allowed clustering by column, increased the size of the plot, and altered the documentation, tab title, and heat map title as well to hopefully better describe the purpose of the plot.

@sjessa I'm wondering if you think additional bars at the top of the plot (categorizing the cell clusters) would be helpful: for example a bar for Forebrain vs. Pons, and a bar for timepoints? Let me know what you think.

**Comment by bhavyaac** [comment]
I've just updated the tab to allow the user to select cell types to include in the heat map: 
<img width="1891" alt="Screen Shot 2021-07-28 at 6 14 32 PM" src="https://user-images.githubusercontent.com/26724860/127403579-a20d751a-97b5-4ef1-9ed0-807a68c56700.png">

An error will occur (using `validate()`) if none of the cell types are selected.

I'm going to migrate the remaining features that have been discussed here (i.e. nested selection of granular cell types, additional bars for categorizing clusters) to separate issues so that I can tackle them later on.

**Comment by sjessa** [comment]
@bhavyaac Looks great! Last thing -- is it possible to use a longer name for certain cell types in the sidebar? e.g. "Progenitors/cyc." --> "Progenitors/cycling" and "Non-neuroect." --> "Non-neuroectoderm", just for clarity

Definitely not a big deal, though!
